### ISSUE TITLE
Comments on Ethereum bridge spec

### ISSUE THREAD

**Issue by cwgoes** [anoma/spec#57]
- The M1 Ethereum bridge might allow for transferring tokens from M1 to Ethereum in the future, but that will be added in a future version of the bridge spec.
- "Ethereum blocks have been seen _and validated_ by at least 2/3 of the staking validators" (validators are running Ethereum full nodes)
  - also, we don't need validators to individually mark messages as seen (though we can I guess), we just need to check them against the header - we should check which is cheaper
- validators should include all Ethereum headers which _they_ have marked seen, even if the chain hasn't reached 2/3 yet on one or more of the ancestors

**Comment by batconjurer** [comment]
For your second point, they aren't marking messages as I seen. Since we aren't storing the entire block, we need to keep the relevant messages from the block somehow. So we submit a vote for a blob of data which includes
 * block header
 * block hash
 * the messages from the block we need to keep
 I tried to make this clearer in the spec

**Comment by batconjurer** [comment]
As for the other two points, I made the relevant changes. I wish commenting we a little easier. I had to dig a bit to find what your comments applied to.

**Comment by cwgoes** [comment]
I agree, an issue as a method of commenting is not great. If we move to making PRs for specs instead I can comment there.

**Comment by cwgoes** [comment]
All addressed, thanks :)
